In [ ]:
!python --version

Python 3.10.12

In [ ]:
CAMINHO_DATA = ''

In [ ]:
CAMINHO_BY_GENRE = ''

In [ ]:
CAMINHO_BY_YEAR = ''

In [ ]:
SEED = 1224

# imports
---

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
np.random.seed(SEED)

In [ ]:
import plotly.express as px

In [ ]:
import plotly.graph_objects as go

In [ ]:
import plotly.io as pio
pio.templates.default = 'presentation'

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

# análise dos dados
---

In [ ]:
dados = pd.read_csv(CAMINHO_DATA)
dados_gen = pd.read_csv(CAMINHO_BY_GENRE)
dados_anos = pd.read_csv(CAMINHO_BY_YEAR)

In [ ]:
dados.head(10)

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,speechiness,tempo,artists_song
0,0.285,2000,0.002390,Coldplay,0.429,266773,0.661,0,3AJwUDP919kvQ9QcozQPxg,0.000121,11,0.2340,-7.227,1,Yellow,84,0.0281,173.372,Coldplay - Yellow
1,0.613,2000,0.143000,OutKast,0.843,270507,0.806,1,0I3q5fE6wg7LIfHGngUTnV,0.000000,4,0.0771,-5.946,0,Ms. Jackson,80,0.2690,94.948,OutKast - Ms. Jackson
2,0.400,2000,0.009580,Linkin Park,0.556,216880,0.864,0,60a0Rd6pjrkxjPbaKzXjfq,0.000000,3,0.2090,-5.870,0,In the End,84,0.0584,105.143,Linkin Park - In the End
3,0.543,2000,0.006640,3 Doors Down,0.545,233933,0.865,0,6ZOBP3NvffbU4SZcrnt1k6,0.000011,11,0.1680,-5.708,0,Kryptonite,78,0.0286,99.009,3 Doors Down - Kryptonite
4,0.760,2000,0.030200,Eminem,0.949,284200,0.661,1,3yfqSUWxFvZELEM4PmlwIR,0.000000,5,0.0454,-4.244,0,The Real Slim Shady,80,0.0572,104.504,Eminem - The Real Slim Shady
5,0.941,2000,0.000996,Disturbed,0.695,279213,0.876,1,40rvBMQizxkIqnjPdEWY1v,0.000007,3,0.1060,-4.262,0,Down with the Sickness,76,0.0553,89.954,Disturbed - Down with the Sickness
6,0.722,2000,0.061600,Nelly,0.850,291782,0.700,1,3Gf5nttwcX9aaSQXRWidEZ,0.000002,7,0.2440,-6.490,1,Ride Wit Me,74,0.0478,101.875,Nelly - Ride Wit Me
7,0.507,2000,0.037100,Eminem,0.780,404107,0.768,1,3UmaczJpikHgJFyBTAJVoz,0.000002,6,0.5180,-4.325,0,Stan,78,0.2380,80.063,Eminem - Stan
8,0.861,2000,0.031000,*NSYNC,0.610,200400,0.926,0,62bOmKYxYg7dhrC6gH9vFn,0.001200,8,0.0821,-4.843,0,Bye Bye Bye,71,0.0479,172.638,*NSYNC - Bye Bye Bye
9,0.894,2000,0.300000,Britney Spears,0.751,211160,0.834,0,6naxalmIoLFWR0siv8dnQQ,0.000018,1,0.3550,-5.444,0,Oops!...I Did It Again,78,0.0437,95.053,Britney Spears - Oops!...I Did It Again

In [ ]:
dados['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [ ]:
f'{dados.shape[0]} linhas, {dados.shape[1]} colunas'

'20311 linhas, 19 colunas'

In [ ]:
dados[['explicit', 'key', 'mode']]

       explicit  key  mode
0             0   11     1
1             1    4     0
2             0    3     0
3             0   11     0
4             1    5     0
...         ...  ...   ...
20306         0    9     1
20307         0    6     0
20308         0    7     1
20309         1    0     1
20310         1    2     1

[20311 rows x 3 columns]

In [ ]:
dados = dados.drop(['explicit', 'key', 'mode'], axis='columns')

In [ ]:
dados.columns

Index(['valence', 'year', 'acousticness', 'artists', 'danceability',
       'duration_ms', 'energy', 'id', 'instrumentalness', 'liveness',
       'loudness', 'name', 'popularity', 'speechiness', 'tempo',
       'artists_song'],
      dtype='object')

In [ ]:
f'{dados.shape[0]} linhas, {dados.shape[1]} colunas'

'20311 linhas, 16 colunas'

In [ ]:
dados.isna().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
id                  0
instrumentalness    0
liveness            0
loudness            0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [ ]:
dados_gen.head(10)

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
5,1,abstract,0.459210,0.516167,3.431965e+05,0.442417,0.849667,0.118067,-15.472083,0.046517,127.885750,0.307325,43.500000,1
6,1,abstract beats,0.342147,0.623000,2.299362e+05,0.527800,0.333603,0.099653,-7.918000,0.116373,112.413800,0.493507,58.933333,10
7,1,abstract hip hop,0.243854,0.694571,2.318492e+05,0.646235,0.024231,0.168543,-7.349328,0.214258,108.244987,0.571391,39.790702,2
8,0,accordeon,0.323000,0.588000,1.640000e+05,0.392000,0.441000,0.079400,-14.899000,0.072700,109.131000,0.709000,39.000000,2
9,1,accordion,0.446125,0.624812,1.670616e+05,0.373437,0.193738,0.160300,-14.487063,0.078537,112.872438,0.658688,21.937500,2

In [ ]:
dados_gen = dados_gen.drop(['key', 'mode'], axis='columns')

In [ ]:
dados_gen.columns

Index(['genres', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
       'valence', 'popularity'],
      dtype='object')

In [ ]:
dados_gen.isna().sum()

genres              0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
dtype: int64

In [ ]:
dados_anos.head(10)

,mode,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,1921,0.886896,0.418597,260537.166667,0.231815,0.344878,0.205710,-17.048667,0.073662,101.531493,0.379327,0.653333,2
1,1,1922,0.938592,0.482042,165469.746479,0.237815,0.434195,0.240720,-19.275282,0.116655,100.884521,0.535549,0.140845,10
2,1,1923,0.957247,0.577341,177942.362162,0.262406,0.371733,0.227462,-14.129211,0.093949,114.010730,0.625492,5.389189,0
3,1,1924,0.940200,0.549894,191046.707627,0.344347,0.581701,0.235219,-14.231343,0.092089,120.689572,0.663725,0.661017,10
4,1,1925,0.962607,0.573863,184986.924460,0.278594,0.418297,0.237668,-14.146414,0.111918,115.521921,0.621929,2.604317,5
5,1,1926,0.660817,0.599880,156881.657475,0.211467,0.333093,0.232370,-18.492538,0.483704,109.648033,0.436910,1.422351,9
6,1,1927,0.936179,0.648268,184993.598374,0.264321,0.391328,0.168450,-14.422374,0.113610,114.846524,0.659700,0.801626,7
7,1,1928,0.938617,0.534288,214827.906423,0.207948,0.494835,0.175289,-17.191983,0.159911,106.772262,0.495713,1.525773,1
8,1,1929,0.601427,0.647670,168999.412815,0.241801,0.215204,0.236000,-16.530376,0.490001,110.948357,0.636530,0.340336,7
9,1,1930,0.936715,0.518176,195150.285343,0.333524,0.352206,0.221311,-12.869221,0.119910,109.871194,0.616238,0.926715,2

In [ ]:
dados_anos['year'].unique()

array([1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
       1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
       1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
       1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020])

In [ ]:
dados['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [ ]:
dados_anos = dados_anos[dados_anos.year >= 2000]

In [ ]:
dados_anos['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [ ]:
dados_anos = dados_anos.drop(['key', 'mode'], axis='columns')

In [ ]:
dados_anos.columns

Index(['year', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
       'valence', 'popularity'],
      dtype='object')

In [ ]:
dados_anos.head(10)

,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity
79,2000,0.289323,0.590918,242724.642638,0.625413,0.101168,0.197686,-8.247766,0.089205,118.999323,0.559475,46.684049
80,2001,0.286842,0.583318,240307.796010,0.626986,0.107214,0.187026,-8.305095,0.089182,117.765399,0.541479,48.750125
81,2002,0.282624,0.576160,239503.283000,0.641270,0.088048,0.193911,-7.686640,0.084308,119.239738,0.542397,48.655500
82,2003,0.256471,0.575763,244670.575230,0.660165,0.083049,0.196976,-7.485545,0.093926,120.914622,0.530504,48.626407
83,2004,0.280559,0.567680,237378.708037,0.648868,0.077934,0.202199,-7.601655,0.094239,121.290346,0.524489,49.273143
84,2005,0.255764,0.572281,237229.588205,0.653209,0.090194,0.190082,-7.466159,0.093334,121.617967,0.532531,50.953333
85,2006,0.279986,0.568230,234042.914359,0.650326,0.077701,0.188289,-7.265501,0.085847,121.798615,0.520028,51.313846
86,2007,0.254081,0.563414,241049.962564,0.668305,0.072957,0.196127,-7.044536,0.084347,124.087516,0.516794,51.075897
87,2008,0.249192,0.579193,240107.315601,0.671461,0.063662,0.198431,-6.843804,0.077356,123.509934,0.527542,50.630179
88,2009,0.261929,0.564190,238140.013265,0.670749,0.075872,0.205252,-7.046015,0.085458,123.463808,0.507170,51.440816

In [ ]:
dados_anos = dados_anos.reset_index()
dados_anos.head(10)

,index,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity
0,79,2000,0.289323,0.590918,242724.642638,0.625413,0.101168,0.197686,-8.247766,0.089205,118.999323,0.559475,46.684049
1,80,2001,0.286842,0.583318,240307.796010,0.626986,0.107214,0.187026,-8.305095,0.089182,117.765399,0.541479,48.750125
2,81,2002,0.282624,0.576160,239503.283000,0.641270,0.088048,0.193911,-7.686640,0.084308,119.239738,0.542397,48.655500
3,82,2003,0.256471,0.575763,244670.575230,0.660165,0.083049,0.196976,-7.485545,0.093926,120.914622,0.530504,48.626407
4,83,2004,0.280559,0.567680,237378.708037,0.648868,0.077934,0.202199,-7.601655,0.094239,121.290346,0.524489,49.273143
5,84,2005,0.255764,0.572281,237229.588205,0.653209,0.090194,0.190082,-7.466159,0.093334,121.617967,0.532531,50.953333
6,85,2006,0.279986,0.568230,234042.914359,0.650326,0.077701,0.188289,-7.265501,0.085847,121.798615,0.520028,51.313846
7,86,2007,0.254081,0.563414,241049.962564,0.668305,0.072957,0.196127,-7.044536,0.084347,124.087516,0.516794,51.075897
8,87,2008,0.249192,0.579193,240107.315601,0.671461,0.063662,0.198431,-6.843804,0.077356,123.509934,0.527542,50.630179
9,88,2009,0.261929,0.564190,238140.013265,0.670749,0.075872,0.205252,-7.046015,0.085458,123.463808,0.507170,51.440816

In [ ]:
dados_anos.isna().sum()

index               0
year                0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
dtype: int64

# análise gráfica
---

In [ ]:
px.line(dados_anos, x='year', y='loudness', markers=True,
        title='variação do loudness conforme os anos').show()

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['acousticness'], name='acousticness'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['valence'], name='valence'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['danceability'], name='danceability'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['energy'], name='energy'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['instrumentalness'], name='instrumentalness'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['liveness'], name='liveness'))
fig.add_trace(go.Scatter(
    x=dados_anos['year'], y=dados_anos['speechiness'], name='speechiness'))
fig.show()

In [ ]:
fig = px.imshow(dados.select_dtypes(
    include=[np.number]).corr(), text_auto=True)
fig.update_layout(xaxis=dict(tickangle=45))
fig.show()

1. Loudness altamente correlacionado com Energy
  
  Músicas mais agitadas e altamente enérgicas tem um nível muito maior de sonoridade do que as outras, como as músicas eletrônicas em relação às músicas lo-fi.
2. Loudness inversamente correlacionado com Instrumentalness e Acusticness
  
  Trás a tona um pouco da primeira teoria, mas basicamente músicas mais calmas, com grande número de instrumentais em períodos maiores e acústicas tendem a ser mais “baixas” em termos de volume da sonoridade.
3. Popularity diretamente proporcional com Year
  
  Provavelmente as músicas recomendadas no TOP 50 do Spotify são ouvidas por mais pessoas, o que faz com que crie essa taxa de correlação.

# clusterização por gênero
---

## pca e standardscaler

In [ ]:
f'{dados_gen.shape[0]} linhas, {dados_gen.shape[1]} colunas'

'2973 linhas, 12 colunas'

In [ ]:
dados_gen['genres'].value_counts().sum()

2973

In [ ]:
dados_gen1 = dados_gen.drop('genres', axis='columns')
dados_gen1.columns

Index(['acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
       'valence', 'popularity'],
      dtype='object')

Agora vamos utilizar vários conceitos em um processo de pipeline, então a primeira coisa que vamos fazer é importar o método Pipeline do sklearn.pipeline e esse método faz literalmente uma pipeline de machine learning, mas de uma forma automática, onde aplica sequencialmente uma lista de transformações até um resultado final. Então o que precisamos passar é o que a nossa pipeline vai fazer, como o primeiro passo e o que queremos de resultado final dela.

Neste ponto precisamos reduzir a dimensionalidade da tabela que está com várias colunas, porém se utilizarmos um processo de redução diretamente, sem fazer a padronização dos dados na parte de pré processamento, os resultados ficarão totalmente desbalanceados, trazendo maior peso para as variáveis que têm uma amplitude maior, como por exemplo o loudness em relação às outras variáveis que compõem a música.

Para resolver esse problema, o primeiro passo da pipeline vai ser usar o StandardScaler para trazer essa padronização e redução de escala para que no próximo passo seja feita a redução de dimensionalidade com um método de decomposição, no nosso caso vamos escolher o PCA.

PCA significa Análise de componentes principais e ele trás consigo uma série de análises matemáticas que são feitas para que possamos transformar aquelas milhares de colunas que temos em uma quantidade menor, com um valor n que escolhermos, porém, quanto mais colunas a gente tem no dataset original e menos colunas queremos no dataset final, o aprendizado depois pode ser prejudicado.

Na parte n_components podemos colocar a quantidade de % de explicação que queremos que o algoritmo tenha no final, como por exemplo 0.3, que seria 30%, ou um valor como por exemplo um valor X de colunas.

Depois de feita a pipeline, vamos salvar em um arquivo chamado projection, com as colunas x e y, que são as posições dos pontos na cluster.

In [ ]:
pca_pipeline = Pipeline([('scaler', StandardScaler()),
                        ('PCA', PCA(n_components=2, random_state=SEED))])

In [ ]:
genre_embedding_pca = pca_pipeline.fit_transform(dados_gen1)

In [ ]:
projection = pd.DataFrame(columns=['x', 'y'], data=genre_embedding_pca)
projection

             x         y
0     5.910268 -0.011146
1     2.787093  4.498483
2    -0.757538 -1.258495
3     1.020521 -0.931690
4     0.753911 -0.999861
...        ...       ...
2968 -0.475136 -0.017126
2969 -3.026756 -1.304983
2970 -0.832511 -1.089726
2971  1.774790 -3.695233
2972 -1.028069 -1.390709

[2973 rows x 2 columns]

In [ ]:
px.scatter(projection, x='x', y='y', title='projection scatter',
           labels={'x': 'x-axis', 'y': 'y-axis'}).show()

# k-means
---

In [ ]:
kmeans_pca = KMeans(n_clusters=5, verbose=False, random_state=SEED, n_init=10)

In [ ]:
kmeans_pca.fit(projection)

KMeans(n_clusters=5, n_init=10, random_state=1224, verbose=False)

In [ ]:
dados_gen['cluster_pca'] = kmeans_pca.predict(projection)
projection['cluster_pca'] = kmeans_pca.predict(projection)

In [ ]:
projection

             x         y  cluster_pca
0     5.910268 -0.011146            3
1     2.787093  4.498483            3
2    -0.757538 -1.258495            4
3     1.020521 -0.931690            1
4     0.753911 -0.999861            1
...        ...       ...          ...
2968 -0.475136 -0.017126            2
2969 -3.026756 -1.304983            4
2970 -0.832511 -1.089726            4
2971  1.774790 -3.695233            1
2972 -1.028069 -1.390709            4

[2973 rows x 3 columns]

In [ ]:
projection['genres'] = dados_gen['genres']

In [ ]:
projection

             x         y  cluster_pca                  genres
0     5.910268 -0.011146            3  21st century classical
1     2.787093  4.498483            3                   432hz
2    -0.757538 -1.258495            4                   8-bit
3     1.020521 -0.931690            1                      []
4     0.753911 -0.999861            1              a cappella
...        ...       ...          ...                     ...
2968 -0.475136 -0.017126            2                    zolo
2969 -3.026756 -1.304983            4                 zouglou
2970 -0.832511 -1.089726            4                    zouk
2971  1.774790 -3.695233            1            zurich indie
2972 -1.028069 -1.390709            4                  zydeco

[2973 rows x 4 columns]

# plotando o clustering
---

In [ ]:
px.scatter(projection, x='x', y='y', color='cluster_pca',
           hover_data=['x', 'y', 'genres']).show()

In [ ]:
pca_pipeline[1].explained_variance_ratio_

array([0.34986105, 0.14284565])

In [ ]:
pca_pipeline[1].explained_variance_ratio_.sum()

0.49270669947266443

In [ ]:
pca_pipeline[1].explained_variance_

array([3.84976644, 1.57183087])

In [ ]:
pca_pipeline[1].explained_variance_.sum()

5.421597305805701

Em duas colunas estamos conseguindo explicar 5 das 11 colunas totais que tínhamos.

# redução de dimensionalidade
---

In [ ]:
 dados.head(10)

,valence,year,acousticness,artists,danceability,duration_ms,energy,id,instrumentalness,liveness,loudness,name,popularity,speechiness,tempo,artists_song
0,0.285,2000,0.002390,Coldplay,0.429,266773,0.661,3AJwUDP919kvQ9QcozQPxg,0.000121,0.2340,-7.227,Yellow,84,0.0281,173.372,Coldplay - Yellow
1,0.613,2000,0.143000,OutKast,0.843,270507,0.806,0I3q5fE6wg7LIfHGngUTnV,0.000000,0.0771,-5.946,Ms. Jackson,80,0.2690,94.948,OutKast - Ms. Jackson
2,0.400,2000,0.009580,Linkin Park,0.556,216880,0.864,60a0Rd6pjrkxjPbaKzXjfq,0.000000,0.2090,-5.870,In the End,84,0.0584,105.143,Linkin Park - In the End
3,0.543,2000,0.006640,3 Doors Down,0.545,233933,0.865,6ZOBP3NvffbU4SZcrnt1k6,0.000011,0.1680,-5.708,Kryptonite,78,0.0286,99.009,3 Doors Down - Kryptonite
4,0.760,2000,0.030200,Eminem,0.949,284200,0.661,3yfqSUWxFvZELEM4PmlwIR,0.000000,0.0454,-4.244,The Real Slim Shady,80,0.0572,104.504,Eminem - The Real Slim Shady
5,0.941,2000,0.000996,Disturbed,0.695,279213,0.876,40rvBMQizxkIqnjPdEWY1v,0.000007,0.1060,-4.262,Down with the Sickness,76,0.0553,89.954,Disturbed - Down with the Sickness
6,0.722,2000,0.061600,Nelly,0.850,291782,0.700,3Gf5nttwcX9aaSQXRWidEZ,0.000002,0.2440,-6.490,Ride Wit Me,74,0.0478,101.875,Nelly - Ride Wit Me
7,0.507,2000,0.037100,Eminem,0.780,404107,0.768,3UmaczJpikHgJFyBTAJVoz,0.000002,0.5180,-4.325,Stan,78,0.2380,80.063,Eminem - Stan
8,0.861,2000,0.031000,*NSYNC,0.610,200400,0.926,62bOmKYxYg7dhrC6gH9vFn,0.001200,0.0821,-4.843,Bye Bye Bye,71,0.0479,172.638,*NSYNC - Bye Bye Bye
9,0.894,2000,0.300000,Britney Spears,0.751,211160,0.834,6naxalmIoLFWR0siv8dnQQ,0.000018,0.3550,-5.444,Oops!...I Did It Again,78,0.0437,95.053,Britney Spears - Oops!...I Did It Again

In [ ]:
dados['artists'].value_counts()

artists
Drake                   170
Taylor Swift            156
Eminem                  147
Kanye West              136
BTS                     122
                       ...
Of Monsters and Men       7
The Living Tombstone      7
Clean Bandit              7
Nelly Furtado             6
Empire of the Sun         6
Name: count, Length: 875, dtype: int64

In [ ]:
dados['artists_song'].value_counts()

artists_song
Coldplay - Yellow                                                   1
Juice WRLD - Intro                                                  1
Carrie Underwood - The Champion - Bonus Track                       1
YoungBoy Never Broke Again - Cross Me (feat. Lil Baby and Plies)    1
Twenty One Pilots - Morph                                           1
                                                                   ..
Taylor Swift - Come Back...Be Here                                  1
Banda El Recodo - Me Gusta Todo De Ti                               1
Michael Bublé - The Christmas Song                                  1
Glee Cast - Smooth Criminal (Glee Cast Version) (feat. 2CELLOS)     1
Eminem - Darkness                                                   1
Name: count, Length: 20311, dtype: int64

In [ ]:
ohe = OneHotEncoder(dtype=int)

In [ ]:
colunas_ohe = ohe.fit_transform(dados[['artists']]).toarray()

In [ ]:
dados2 = dados.drop('artists', axis=1)

In [ ]:
dados_msc_dummies = pd.concat([dados2, pd.DataFrame(
    colunas_ohe, columns=ohe.get_feature_names_out(['artists']))], axis=1)
dados_msc_dummies

,valence,year,acousticness,danceability,duration_ms,energy,id,instrumentalness,liveness,loudness,...,artists_Zara Larsson,artists_Zedd,artists_alt-J,artists_blackbear,artists_blink-182,artists_deadmau5,artists_for KING & COUNTRY,artists_fun.,artists_girl in red,artists_iann dior
0,0.285,2000,0.00239,0.429,266773,0.661,3AJwUDP919kvQ9QcozQPxg,0.000121,0.2340,-7.227,...,0,0,0,0,0,0,0,0,0,0
1,0.613,2000,0.14300,0.843,270507,0.806,0I3q5fE6wg7LIfHGngUTnV,0.000000,0.0771,-5.946,...,0,0,0,0,0,0,0,0,0,0
2,0.400,2000,0.00958,0.556,216880,0.864,60a0Rd6pjrkxjPbaKzXjfq,0.000000,0.2090,-5.870,...,0,0,0,0,0,0,0,0,0,0
3,0.543,2000,0.00664,0.545,233933,0.865,6ZOBP3NvffbU4SZcrnt1k6,0.000011,0.1680,-5.708,...,0,0,0,0,0,0,0,0,0,0
4,0.760,2000,0.03020,0.949,284200,0.661,3yfqSUWxFvZELEM4PmlwIR,0.000000,0.0454,-4.244,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20306,0.187,2020,0.57400,0.445,176250,0.330,0PUkanqCGTb6qseXPKOw1F,0.000000,0.1020,-8.121,...,0,0,0,0,0,0,0,0,0,0
20307,0.240,2020,0.81500,0.467,179188,0.429,6Iw6fQVKZi0fWtEQBrTFcP,0.000052,0.1770,-8.689,...,0,0,0,0,0,0,0,0,0,0
20308,0.466,2020,0.31000,0.562,253613,0.686,308prODCCD0O660tIktbUi,0.022500,0.1250,-8.480,...,0,0,0,0,0,0,0,0,0,0
20309,0.522,2020,0.20400,0.598,230600,0.472,2f8y4CuG57UJEmkG3ujd0D,0.000015,0.1080,-10.991,...,0,0,0,0,0,0,0,0,0,0
20310,0.195,2020,0.00998,0.671,337147,0.623,5SiZJoLXp3WOl3J4C8IK0d,0.000008,0.6430,-7.161,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pca_pipeline = Pipeline([('scaler', StandardScaler()),
                        ('PCA', PCA(n_components=0.7, random_state=SEED))])

In [ ]:
msc_embedding_pca = pca_pipeline.fit_transform(
    dados_msc_dummies.drop(['id', 'name', 'artists_song'], axis=1))

In [ ]:
projection_msc = pd.DataFrame(data=msc_embedding_pca)

In [ ]:
projection_msc

,0,1,2,3,4,5,6,7,8,9,...,602,603,604,605,606,607,608,609,610,611
0,0.174796,0.731252,2.186797,-0.767192,0.594847,0.315968,-0.412322,-0.479171,-2.700668,2.109956,...,0.002516,0.002097,-0.019072,-0.009111,0.005154,-0.034027,-0.032617,2.241192e-11,1.202033e-13,3.177821e-12
1,-1.358420,0.052935,-1.789973,1.938444,0.403606,1.023898,-1.172118,0.821698,-1.716897,0.252498,...,0.036047,-0.026825,-0.031678,-0.031986,0.029708,-0.016322,-0.030234,-2.395758e-12,2.291641e-13,-1.187264e-12
2,-0.972077,0.658094,0.757500,-0.277350,-0.400393,0.402941,1.292960,1.839192,-1.562236,1.410677,...,-0.013908,0.007214,0.003084,0.017097,0.017361,-0.010979,-0.012781,4.273933e-12,-6.407207e-13,-1.958694e-13
3,-0.926464,1.292091,0.398499,-0.997738,0.202219,0.620859,-0.527689,1.135529,-1.343893,1.020964,...,0.038784,0.020814,-0.046126,0.089337,0.164777,-0.064148,-0.040911,5.152080e-11,-7.249490e-13,1.084807e-11
4,-1.710077,-0.383502,-1.258562,1.346428,1.223591,1.744579,0.094311,0.479412,-2.125376,0.389565,...,0.006291,0.003111,-0.009148,-0.011937,-0.004081,-0.017478,-0.010033,2.254040e-12,1.683896e-13,8.389616e-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20306,1.346699,-2.775889,0.986755,-1.704967,0.103935,-0.726582,0.253808,0.520234,-0.064513,0.204971,...,-0.155320,0.335148,0.103481,-0.235355,-0.054256,0.016922,-0.125947,4.217717e-11,-4.175589e-13,5.457610e-11
20307,1.269387,-2.444619,0.971408,-0.115303,-0.719597,-1.823579,-0.545186,-1.475719,-0.338390,0.272129,...,0.264741,0.210461,-0.094337,-0.183026,0.074605,0.005622,0.000054,4.323403e-11,1.154738e-11,9.481307e-12
20308,0.781916,-1.164865,0.705256,-0.947160,1.145828,-0.472667,-0.356604,0.972512,0.900317,-0.674016,...,0.263781,-0.189241,0.213993,-0.033420,-0.157564,0.213849,-0.065180,-2.580928e-11,9.953739e-12,4.430351e-11
20309,0.002454,-3.056407,-0.272934,1.436355,-0.604453,0.251492,-1.361710,-0.633245,0.280076,0.521145,...,0.398941,0.560966,-0.437674,-0.784640,0.080684,0.038379,0.108493,5.473520e-11,1.333316e-11,1.185832e-11
20310,-0.957008,-1.208016,1.103144,4.128170,1.026126,0.085505,1.588383,0.567041,-1.026283,0.266124,...,0.005936,0.003050,-0.009230,-0.012069,-0.003818,-0.017675,-0.010372,2.372825e-12,1.582875e-13,8.373194e-13

In [ ]:
pca_pipeline[1].n_components_

612

# aplicação do cluster
---

In [ ]:
kmeans_pca_pipeline = KMeans(
    n_clusters=50, verbose=False, random_state=SEED, n_init=10)

In [ ]:
kmeans_pca_pipeline.fit(projection_msc)

KMeans(n_clusters=50, n_init=10, random_state=1224, verbose=False)

In [ ]:
dados['cluster_pca'] = kmeans_pca_pipeline.predict(projection_msc)
projection_msc['cluster_pca'] = kmeans_pca_pipeline.predict(projection_msc)

In [ ]:
projection_msc['artist'] = dados['artists']
projection_msc['song'] = dados['artists_song']

In [ ]:
projection_msc

,0,1,2,3,4,5,6,7,8,9,...,605,606,607,608,609,610,611,cluster_pca,artist,song
0,0.174796,0.731252,2.186797,-0.767192,0.594847,0.315968,-0.412322,-0.479171,-2.700668,2.109956,...,-0.009111,0.005154,-0.034027,-0.032617,2.241192e-11,1.202033e-13,3.177821e-12,5,Coldplay,Coldplay - Yellow
1,-1.358420,0.052935,-1.789973,1.938444,0.403606,1.023898,-1.172118,0.821698,-1.716897,0.252498,...,-0.031986,0.029708,-0.016322,-0.030234,-2.395758e-12,2.291641e-13,-1.187264e-12,12,OutKast,OutKast - Ms. Jackson
2,-0.972077,0.658094,0.757500,-0.277350,-0.400393,0.402941,1.292960,1.839192,-1.562236,1.410677,...,0.017097,0.017361,-0.010979,-0.012781,4.273933e-12,-6.407207e-13,-1.958694e-13,20,Linkin Park,Linkin Park - In the End
3,-0.926464,1.292091,0.398499,-0.997738,0.202219,0.620859,-0.527689,1.135529,-1.343893,1.020964,...,0.089337,0.164777,-0.064148,-0.040911,5.152080e-11,-7.249490e-13,1.084807e-11,12,3 Doors Down,3 Doors Down - Kryptonite
4,-1.710077,-0.383502,-1.258562,1.346428,1.223591,1.744579,0.094311,0.479412,-2.125376,0.389565,...,-0.011937,-0.004081,-0.017478,-0.010033,2.254040e-12,1.683896e-13,8.389616e-13,12,Eminem,Eminem - The Real Slim Shady
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20306,1.346699,-2.775889,0.986755,-1.704967,0.103935,-0.726582,0.253808,0.520234,-0.064513,0.204971,...,-0.235355,-0.054256,0.016922,-0.125947,4.217717e-11,-4.175589e-13,5.457610e-11,30,Bazzi,Bazzi - I Don't Think I'm Okay
20307,1.269387,-2.444619,0.971408,-0.115303,-0.719597,-1.823579,-0.545186,-1.475719,-0.338390,0.272129,...,-0.183026,0.074605,0.005622,0.000054,4.323403e-11,1.154738e-11,9.481307e-12,30,Bryson Tiller,Bryson Tiller - Timeless Interlude
20308,0.781916,-1.164865,0.705256,-0.947160,1.145828,-0.472667,-0.356604,0.972512,0.900317,-0.674016,...,-0.033420,-0.157564,0.213849,-0.065180,-2.580928e-11,9.953739e-12,4.430351e-11,30,Fleet Foxes,Fleet Foxes - Sunblind
20309,0.002454,-3.056407,-0.272934,1.436355,-0.604453,0.251492,-1.361710,-0.633245,0.280076,0.521145,...,-0.784640,0.080684,0.038379,0.108493,5.473520e-11,1.333316e-11,1.185832e-11,30,Gunna,Gunna - NASTY GIRL / ON CAMERA
20310,-0.957008,-1.208016,1.103144,4.128170,1.026126,0.085505,1.588383,0.567041,-1.026283,0.266124,...,-0.012069,-0.003818,-0.017675,-0.010372,2.372825e-12,1.582875e-13,8.373194e-13,30,Eminem,Eminem - Darkness

# analisando o cluster
---

In [ ]:
px.scatter(projection_msc, x=0, y=1, color='cluster_pca',
           hover_data=[0, 1, 'song']).show()

In [ ]:
pca_pipeline[1].explained_variance_ratio_.sum()

0.7000008463187031

In [ ]:
pca_pipeline[1].explained_variance_.sum()

620.9313218688688

In [ ]:
px.scatter_3d(projection_msc, x=0, y=1, z=2, color='cluster_pca',
              hover_data=['song']).update_traces(marker_size=2).show()

# recomendação da música
---

In [ ]:
nome_música = 'Mac Miller - Objects in the Mirror'

In [ ]:
projection_msc['song']

0                         Coldplay - Yellow
1                     OutKast - Ms. Jackson
2                  Linkin Park - In the End
3                 3 Doors Down - Kryptonite
4              Eminem - The Real Slim Shady
                        ...
20306        Bazzi - I Don't Think I'm Okay
20307    Bryson Tiller - Timeless Interlude
20308                Fleet Foxes - Sunblind
20309        Gunna - NASTY GIRL / ON CAMERA
20310                     Eminem - Darkness
Name: song, Length: 20311, dtype: object

In [ ]:
cluster = list(projection_msc[projection_msc['song']
               == nome_música]['cluster_pca'])[0]
cluster

30

In [ ]:
músicas_recomendadas = projection_msc[projection_msc['cluster_pca'] == cluster][[
    0, 1, 'song']]
músicas_recomendadas

              0         1                                         song
576    1.155518  0.412391                             Sia - Breathe Me
670   -0.632877 -0.632693            Chris Brown - Yo (Excuse Me Miss)
690   -0.430718 -0.784600  Chris Brown - Run It! (feat. Juelz Santana)
812   -1.501584 -1.101391                        Fergie - Fergalicious
833   -0.498946 -0.682435      Fergie - Big Girls Don't Cry (Personal)
...         ...       ...                                          ...
20306  1.346699 -2.775889               Bazzi - I Don't Think I'm Okay
20307  1.269387 -2.444619           Bryson Tiller - Timeless Interlude
20308  0.781916 -1.164865                       Fleet Foxes - Sunblind
20309  0.002454 -3.056407               Gunna - NASTY GIRL / ON CAMERA
20310 -0.957008 -1.208016                            Eminem - Darkness

[5201 rows x 3 columns]

In [ ]:
x_música = list(projection_msc[projection_msc['song'] == nome_música][0])[0]
y_música = list(projection_msc[projection_msc['song'] == nome_música][1])[0]

In [ ]:
distâncias = euclidean_distances(
    músicas_recomendadas[[0, 1]], [[x_música, y_música]])

In [ ]:
músicas_recomendadas['id'] = dados['id']
músicas_recomendadas['distâncias'] = distâncias

In [ ]:
músicas_recomendadas.sort_values('distâncias').head(10)

,0,1,song,id,distâncias
4529,0.754372,-1.163977,Mac Miller - Objects in the Mirror,64gyqTtDDel7B2NoEkOa0A,0.000000
6815,0.739863,-1.162920,Kendrick Lamar - Sherane a.k.a Master Splinter...,0qGFnxDIqGBIq2D3zNbjk9,0.014547
20308,0.781916,-1.164865,Fleet Foxes - Sunblind,308prODCCD0O660tIktbUi,0.027559
17144,0.768031,-1.206676,Fleet Foxes - Can I Believe You,3pYB28IRzhtR5cHXLINchp,0.044830
11470,0.800679,-1.191251,Lana Del Rey - Cherry,1Ym6aMuT5bliaZMC67AmPp,0.053742
11056,0.728635,-1.112564,Drake - Connect,4K3BhUMfBHZuUfeC3kbhrQ,0.057496
1675,0.711831,-1.208000,Mac Miller - Missed Calls,6ET22Ri3FYXi5C8BBqHWcO,0.061219
11144,0.682541,-1.154819,Jon Bellion - Luxury,5CgFGKdTn8R5dXGEPEX6Gm,0.072413
9626,0.819442,-1.199452,Hozier - Movement,1djzKW3eYLyzjjHXazEWWh,0.074112
9284,0.677344,-1.136773,Troye Sivan - BITE,72mvdKU4Lw2737idPLKTjh,0.081690